services:
  astro_chat_db:
    image: postgres # Uses the official PostgreSQL image
    environment:
      POSTGRES_USER: "root" # Database username (change for production)
      POSTGRES_PASSWORD: "root" # Database password (change for security)
      POSTGRES_DB: "chat" # Name of the database to be created
      PGDATA: /data/postgres # Directory where PostgreSQL stores its data
    ports:
      - "5431:5432" # Maps local port 5431 to the container’s PostgreSQL port 5432
    volumes:
      - astro_chat_db:/data/postgres # Persistent storage for database data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql # Initializes the database with a schema on first run

volumes:
  astro_chat_db: # Defines a named volume to persist PostgreSQL data
    driver: local # Uses the default local volume driver
