CREATE TABLE "User" (
    "id" SERIAL PRIMARY KEY,
    "email" VARCHAR(191) NOT NULL UNIQUE,
    "password" VARCHAR(191) NOT NULL,
    "name" VARCHAR(191) NOT NULL
);

CREATE TABLE "Channel" (
    "id" VARCHAR(191) PRIMARY KEY,
    "name" VARCHAR(191) NOT NULL UNIQUE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Message" (
    "id" SERIAL PRIMARY KEY,
    "content" VARCHAR(191) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "userId" INT NOT NULL,
    "channelId" VARCHAR(191) NOT NULL
);
